# Generated by Django 6.0.2 on 2026-02-20 04:21

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("form_data", models.JSONField(blank=True, default=dict)),
                ("current_step", models.PositiveSmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated: GCLBA-YYYY-NNNN",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("docs_requested", "Documents Requested"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                (
                    "preferred_contact",
                    models.CharField(
                        choices=[("email", "Email"), ("phone", "Phone"), ("text", "Text")],
                        default="email",
                        max_length=10,
                    ),
                ),
                ("street_address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(default="MI", max_length=2)),
                ("zip_code", models.CharField(max_length=10)),
                (
                    "property_address",
                    models.CharField(
                        blank=True,
                        help_text="Address of the property being purchased",
                        max_length=255,
                    ),
                ),
                (
                    "parcel_id",
                    models.CharField(
                        blank=True, help_text="County parcel ID number", max_length=50
                    ),
                ),
                (
                    "program_type",
                    models.CharField(
                        choices=[
                            ("own_it_now", "Own It Now"),
                            ("ready_for_rehab", "Ready for Rehab"),
                        ],
                        default="own_it_now",
                        max_length=20,
                    ),
                ),
                (
                    "attended_open_house",
                    models.BooleanField(
                        default=False, help_text="Has the buyer visited the property?"
                    ),
                ),
                (
                    "open_house_date",
                    models.DateField(blank=True, help_text="Date of open house visit", null=True),
                ),
                (
                    "offer_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Purchase offer in dollars", max_digits=10
                    ),
                ),
                (
                    "purchase_type",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("land_contract", "Land Contract"),
                            ("conventional", "Conventional Mortgage"),
                            ("fha_va", "FHA/VA Loan"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                (
                    "intended_use",
                    models.CharField(
                        choices=[
                            ("primary_residence", "Primary Residence"),
                            ("rental", "Rental Property"),
                            ("rehab_resale", "Rehab & Resale"),
                            ("commercial", "Commercial Use"),
                        ],
                        default="primary_residence",
                        max_length=20,
                    ),
                ),
                (
                    "has_delinquent_taxes",
                    models.BooleanField(
                        default=False,
                        help_text="Does the buyer owe delinquent property taxes in Genesee County?",
                    ),
                ),
                (
                    "has_tax_foreclosure",
                    models.BooleanField(
                        default=False,
                        help_text="Has the buyer lost property to tax foreclosure in Genesee County?",
                    ),
                ),
                (
                    "rehab_scope",
                    models.TextField(
                        blank=True, help_text="Description of planned rehabilitation work"
                    ),
                ),
                (
                    "rehab_budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated rehab budget in dollars",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "rehab_timeline",
                    models.CharField(
                        blank=True,
                        help_text="Expected timeline for rehab completion",
                        max_length=100,
                    ),
                ),
                ("contractor_name", models.CharField(blank=True, max_length=200)),
                ("contractor_phone", models.CharField(blank=True, max_length=20)),
                (
                    "lc_provider_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Land contract provider"
                    ),
                ),
                (
                    "lc_provider_phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Provider phone"),
                ),
                (
                    "lc_term_months",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Contract term (months)"
                    ),
                ),
                (
                    "lc_interest_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Interest rate (%)",
                    ),
                ),
                (
                    "ack_info_accurate",
                    models.BooleanField(
                        default=False, verbose_name="I certify all information is accurate"
                    ),
                ),
                (
                    "ack_terms_conditions",
                    models.BooleanField(
                        default=False, verbose_name="I agree to GCLBA terms and conditions"
                    ),
                ),
                (
                    "ack_inspection_waiver",
                    models.BooleanField(
                        default=False, verbose_name="I understand properties are sold as-is"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member reviewing this application",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("photo_id", "Photo ID"),
                            ("pay_stub_1", "Pay Stub #1"),
                            ("pay_stub_2", "Pay Stub #2"),
                            ("bank_statement", "Bank Statement"),
                            ("proof_of_funds", "Proof of Funds"),
                            ("preapproval", "Pre-Approval Letter"),
                            ("additional_income", "Additional Income Documentation"),
                        ],
                        max_length=30,
                    ),
                ),
                ("file", models.FileField(upload_to="applications/%Y/%m/")),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="applications.application",
                    ),
                ),
            ],
            options={
                "ordering": ["doc_type"],
            },
        ),
        migrations.CreateModel(
            name="StatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=20)),
                ("to_status", models.CharField(max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="applications.application",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
            },
        ),
    ]
