# Generated by Django 6.0.2 on 2026-02-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='idx_app_status'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status', 'program_type'], name='idx_app_status_program'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['-submitted_at'], name='idx_app_submitted'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['email'], name='idx_app_email'),
        ),
    ]
