# Generated by Django 6.0.2 on 2026-02-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='street_address',
            new_name='mailing_address',
        ),
        migrations.RemoveField(
            model_name='application',
            name='ack_inspection_waiver',
        ),
        migrations.RemoveField(
            model_name='application',
            name='ack_terms_conditions',
        ),
        migrations.RemoveField(
            model_name='application',
            name='contractor_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='contractor_phone',
        ),
        migrations.RemoveField(
            model_name='application',
            name='lc_interest_rate',
        ),
        migrations.RemoveField(
            model_name='application',
            name='lc_provider_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='lc_provider_phone',
        ),
        migrations.RemoveField(
            model_name='application',
            name='lc_term_months',
        ),
        migrations.RemoveField(
            model_name='application',
            name='rehab_budget',
        ),
        migrations.RemoveField(
            model_name='application',
            name='rehab_scope',
        ),
        migrations.RemoveField(
            model_name='application',
            name='rehab_timeline',
        ),
        migrations.AddField(
            model_name='application',
            name='ack_highest_not_guaranteed',
            field=models.BooleanField(default=False, verbose_name='I understand the highest offer is not guaranteed to be accepted'),
        ),
        migrations.AddField(
            model_name='application',
            name='ack_no_title_insurance',
            field=models.BooleanField(default=False, verbose_name='I understand GCLBA does not provide title insurance'),
        ),
        migrations.AddField(
            model_name='application',
            name='ack_no_transfer',
            field=models.BooleanField(default=False, verbose_name='I will not transfer or encumber without GCLBA consent'),
        ),
        migrations.AddField(
            model_name='application',
            name='ack_quit_claim_deed',
            field=models.BooleanField(default=False, verbose_name='I understand closing is via Quit Claim Deed'),
        ),
        migrations.AddField(
            model_name='application',
            name='ack_reconveyance_deed',
            field=models.BooleanField(default=False, verbose_name='I acknowledge the reconveyance deed requirement'),
        ),
        migrations.AddField(
            model_name='application',
            name='ack_sold_as_is',
            field=models.BooleanField(default=False, verbose_name='I understand properties are sold as-is'),
        ),
        migrations.AddField(
            model_name='application',
            name='ack_tax_capture',
            field=models.BooleanField(default=False, verbose_name='I understand the 5/50 tax capture waiver requirement'),
        ),
        migrations.AddField(
            model_name='application',
            name='contact_name_different',
            field=models.CharField(blank=True, help_text='If the primary contact is different from the buyer', max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='down_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Land contract down payment (min 10% or $1,000)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='first_home_or_moving',
            field=models.CharField(blank=True, choices=[('first_home', 'First Home Purchase'), ('moving_to_mi', 'Moving to MI from Another State'), ('neither', 'Neither')], help_text='Sub-question when intended use is Renovate & Move In', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='has_prior_gclba_purchase',
            field=models.BooleanField(default=False, help_text='Has applicant previously purchased from GCLBA?'),
        ),
        migrations.AddField(
            model_name='application',
            name='homebuyer_ed_agency',
            field=models.CharField(blank=True, choices=[('metro_community_dev', 'Metro Community Development'), ('habitat_for_humanity', 'Genesee County Habitat for Humanity'), ('fannie_mae_online', 'Fannie Mae (Online)'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='homebuyer_ed_completed',
            field=models.BooleanField(default=False, help_text='Has completed or will complete homebuyer education before closing'),
        ),
        migrations.AddField(
            model_name='application',
            name='homebuyer_ed_other',
            field=models.CharField(blank=True, help_text='Agency name if Other selected', max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='is_self_employed',
            field=models.BooleanField(default=False, help_text='Changes income documentation requirements for land contract'),
        ),
        migrations.AddField(
            model_name='application',
            name='purchasing_entity_name',
            field=models.CharField(blank=True, help_text='If purchasing through an LLC, trust, or other entity', max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='reno_bathroom_repairs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='application',
            name='reno_clean_out',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='application',
            name='reno_cleanup_landscaping',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='application',
            name='reno_demolition_disposal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='application',
            name='reno_doors_ext',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='application',
            name='reno_doors_int',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='application',
            name='reno_drywall_plaster',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='application',
            name='reno_electrical',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='application',
            name='reno_exterior_subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='application',
            name='reno_flooring',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='application',
            name='reno_foundation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='application',
            name='reno_garage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='application',
            name='reno_hvac',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='application',
            name='reno_insulation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='application',
            name='reno_interior_subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='application',
            name='reno_kitchen_appliances',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='application',
            name='reno_kitchen_cabinets',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='application',
            name='reno_lighting_ext',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='application',
            name='reno_lighting_int',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='application',
            name='reno_masonry',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='application',
            name='reno_paint_wallpaper',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='application',
            name='reno_plumbing',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='application',
            name='reno_porch_decking',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='application',
            name='reno_roof',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='application',
            name='reno_siding',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='application',
            name='reno_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='application',
            name='reno_water_heater',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='application',
            name='reno_windows',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='application',
            name='renovation_description',
            field=models.TextField(blank=True, help_text='What renovations will you be making?'),
        ),
        migrations.AddField(
            model_name='application',
            name='renovation_funding',
            field=models.TextField(blank=True, help_text='How will you pay for purchase and renovations?'),
        ),
        migrations.AddField(
            model_name='application',
            name='renovation_when',
            field=models.CharField(blank=True, help_text='When will renovations be completed?', max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='renovation_who',
            field=models.TextField(blank=True, help_text='Who will complete the renovations?'),
        ),
        migrations.AddField(
            model_name='application',
            name='staff_notes',
            field=models.TextField(blank=True, help_text='Internal notes — never visible to buyer'),
        ),
        migrations.AddField(
            model_name='application',
            name='vip_q1_who_and_why',
            field=models.TextField(blank=True, help_text='Who are you and why do you want to purchase this property?'),
        ),
        migrations.AddField(
            model_name='application',
            name='vip_q2_prior_detail',
            field=models.TextField(blank=True, help_text='Details of prior GCLBA purchases'),
        ),
        migrations.AddField(
            model_name='application',
            name='vip_q2_prior_purchases',
            field=models.BooleanField(blank=True, help_text='Have you purchased single-family homes from GCLBA previously?', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='vip_q3_renovation_costs_timeline',
            field=models.TextField(blank=True, help_text='Estimated renovation costs and development timeline'),
        ),
        migrations.AddField(
            model_name='application',
            name='vip_q4_financing',
            field=models.TextField(blank=True, help_text='How do you intend to finance the project?'),
        ),
        migrations.AddField(
            model_name='application',
            name='vip_q5_experience_detail',
            field=models.TextField(blank=True, help_text='Portfolio: addresses, before/after photos'),
        ),
        migrations.AddField(
            model_name='application',
            name='vip_q5_has_experience',
            field=models.BooleanField(blank=True, help_text='Do you have single-family home renovation experience?', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='vip_q6_completion_detail',
            field=models.TextField(blank=True, help_text='Details of completion plan'),
        ),
        migrations.AddField(
            model_name='application',
            name='vip_q6_completion_plan',
            field=models.CharField(blank=True, choices=[('sell', 'Sell'), ('rent', 'Rent')], help_text='Plans upon completion — sell or rent?', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='vip_q7_contractor_info',
            field=models.TextField(blank=True, help_text='Contractor names and Genesee County experience'),
        ),
        migrations.AddField(
            model_name='application',
            name='vip_q8_additional_info',
            field=models.TextField(blank=True, help_text='Letters of support, references, community ties'),
        ),
        migrations.AddField(
            model_name='applicationdraft',
            name='program_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='application',
            name='intended_use',
            field=models.CharField(blank=True, choices=[('renovate_move_in', 'Renovate & Move In'), ('renovate_family', 'Renovate for Family Member'), ('renovate_sell', 'Renovate & Sell'), ('renovate_rent', 'Renovate & Rent Out'), ('demolish', 'Demolish')], max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='offer_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Purchase offer in dollars', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='preferred_contact',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone Call'), ('text', 'Text')], default='email', max_length=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='program_type',
            field=models.CharField(choices=[('featured_homes', 'Featured Homes'), ('ready_for_rehab', 'Ready for Rehab'), ('vip_spotlight', 'VIP Spotlight'), ('vacant_lot', 'Vacant Lot')], default='featured_homes', max_length=30),
        ),
        migrations.AlterField(
            model_name='application',
            name='purchase_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('land_contract', 'Land Contract')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('declined', 'Declined'), ('needs_more_info', 'Needs More Info')], default='received', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('photo_id', 'Photo ID'), ('proof_of_funds', 'Proof of Funds'), ('proof_of_income', 'Proof of Income'), ('proof_of_down_payment', 'Proof of Down Payment'), ('reno_funding_proof', 'Renovation Funding Documentation'), ('prior_investment_proof', 'Prior GCLBA Investment Proof'), ('vip_preapproval', 'Pre-Approval Letter'), ('vip_portfolio_photo', 'Portfolio Photo'), ('vip_support_letter', 'Letter of Support')], max_length=50),
        ),
    ]
