# Generated by Django 6.0.2 on 2026-02-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_four_program_refactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdraft',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicationdraft',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
