# Generated by Django 6.0.2 on 2026-02-24 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_add_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='Property address as it appears in the listing', max_length=255)),
                ('address_normalized', models.CharField(db_index=True, editable=False, help_text='Lowercase, standardized abbreviations for fuzzy matching', max_length=255)),
                ('parcel_id', models.CharField(help_text='Genesee County parcel ID number', max_length=50, unique=True)),
                ('program_type', models.CharField(choices=[('featured_homes', 'Featured Homes'), ('ready_for_rehab', 'Ready for Rehab'), ('vip_spotlight', 'VIP Spotlight'), ('vacant_lot', 'Vacant Lot')], help_text='Which program this property is listed under', max_length=30)),
                ('listing_price', models.DecimalField(blank=True, decimal_places=2, help_text='Listed price in dollars (optional)', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('under_offer', 'Under Offer'), ('sold', 'Sold'), ('withdrawn', 'Withdrawn')], default='available', max_length=20)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('csv_batch', models.CharField(blank=True, help_text='Identifier for the CSV import batch', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'properties',
                'ordering': ['address'],
                'indexes': [models.Index(fields=['program_type', 'status'], name='idx_prop_program_status')],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='property_ref',
            field=models.ForeignKey(blank=True, help_text='Linked property from inventory (null if manually entered)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='applications.property'),
        ),
    ]
