# Generated by Django 6.0.2 on 2026-02-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_property_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='parcel_id',
            field=models.CharField(blank=True, help_text='Genesee County parcel ID number (null allowed for imports without parcel data)', max_length=50, null=True, unique=True),
        ),
    ]
