# Generated by Django 6.0.2 on 2026-02-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_make_parcel_id_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='address_normalized',
            field=models.CharField(editable=False, help_text='Lowercase, standardized abbreviations for fuzzy matching', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='parcel_id',
            field=models.CharField(blank=True, help_text='Genesee County parcel ID number (null allowed for imports without parcel data)', max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.UniqueConstraint(condition=models.Q(('parcel_id__isnull', False)), fields=('parcel_id',), name='unique_parcel_id_when_set'),
        ),
    ]
