# Generated by Django 6.0.2 on 2026-03-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_unique_address_and_parcel_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='document_review',
            field=models.JSONField(blank=True, default=dict, help_text='Per-document review status: {"<doc_pk>": "ok"|"flagged"|"pending"}'),
        ),
    ]
