"""
Django settings for County Landing - Home Sales Application Portal.

Generated by 'django-admin startproject' using Django 6.0.2.
"""

import os
from pathlib import Path

import dj_database_url
from django.urls import reverse_lazy
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Security
_INSECURE_KEY = "django-insecure-dev-only-change-in-production"
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", _INSECURE_KEY)
DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() in ("true", "1", "yes")

# Fail loud if insecure key reaches production
if not DEBUG and SECRET_KEY == _INSECURE_KEY:
    raise RuntimeError(
        "DJANGO_SECRET_KEY must be set in production. "
        "Generate one with: python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'"
    )
ALLOWED_HOSTS = os.getenv(
    "DJANGO_ALLOWED_HOSTS",
    "localhost,127.0.0.1",
).split(",")

CSRF_TRUSTED_ORIGINS = os.getenv(
    "CSRF_TRUSTED_ORIGINS",
    "http://localhost:8000,http://127.0.0.1:8000,"
    "http://localhost:8199,http://127.0.0.1:8199,"
    "https://apply.thelandbank.org,"
    "https://apply-thelandbankorg.up.railway.app",
).split(",")


# Application definition

INSTALLED_APPS = [
    # Unfold must come BEFORE django.contrib.admin
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    # Django core
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party
    "rest_framework",
    "corsheaders",
    "django_htmx",
    "anymail",
    # Local apps
    "applications",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# Uses DATABASE_URL in production (Railway sets this automatically)
# Falls back to SQLite for local development

DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization

LANGUAGE_CODE = "en-us"
TIME_ZONE = "America/New_York"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# WhiteNoise serves these in production without nginx

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# Media files (uploaded documents, images)

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"


# Django REST Framework

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 25,
}


# CORS — only needed if a separate frontend exists (currently server-rendered)

CORS_ALLOWED_ORIGINS = os.getenv(
    "CORS_ALLOWED_ORIGINS",
    "https://apply.thelandbank.org",
).split(",")


# Default primary key field type

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Email — Resend via Anymail in production, console backend for development

EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)
ANYMAIL = {
    "RESEND_API_KEY": os.getenv("RESEND_API_KEY", ""),
}
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "applications@thelandbank.org")
STAFF_NOTIFICATION_EMAIL = os.getenv("STAFF_NOTIFICATION_EMAIL", "offers@thelandbank.org")


# ---------------------------------------------------------------------------
# Security headers — always-on and production-only settings
# ---------------------------------------------------------------------------

SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Railway is a reverse proxy — trust X-Forwarded-Proto
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# ---------------------------------------------------------------------------
# Django Unfold - Admin Theme Configuration
# ---------------------------------------------------------------------------

UNFOLD = {
    "SITE_TITLE": "GCLBA Application Portal",
    "SITE_HEADER": "Genesee County Land Bank",
    "SITE_SUBHEADER": "Application Management",
    "SITE_SYMBOL": "home_work",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": False,

    # Environment indicator (shows "Development" or "Production" badge in header)
    "ENVIRONMENT": "applications.admin_utils.environment_callback",

    # Dashboard stat cards (shown on admin index page)
    "DASHBOARD_CALLBACK": "applications.admin_utils.dashboard_callback",

    # Sidebar navigation with quick filters
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Applications",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "All Applications",
                        "icon": "description",
                        "link": reverse_lazy("admin:applications_application_changelist"),
                        "badge": "applications.admin_utils.pending_count_badge",
                    },
                    {
                        "title": "Drafts (In Progress)",
                        "icon": "edit_note",
                        "link": reverse_lazy("admin:applications_applicationdraft_changelist"),
                    },
                ],
            },
            {
                "title": "Quick Filters",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Needs Review",
                        "icon": "pending_actions",
                        "link": "/admin/applications/application/?status__exact=received",
                    },
                    {
                        "title": "Under Review",
                        "icon": "rate_review",
                        "link": "/admin/applications/application/?status__exact=under_review",
                    },
                    {
                        "title": "Needs More Info",
                        "icon": "upload_file",
                        "link": "/admin/applications/application/?status__exact=needs_more_info",
                    },
                    {
                        "title": "Approved",
                        "icon": "check_circle",
                        "link": "/admin/applications/application/?status__exact=approved",
                    },
                    {
                        "title": "Declined",
                        "icon": "cancel",
                        "link": "/admin/applications/application/?status__exact=declined",
                    },
                ],
            },
            {
                "title": "System",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Users",
                        "icon": "people",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                ],
            },
        ],
    },

    # Theme: civic green primary with blue accents
    "COLORS": {
        "primary": {
            "50": "#f0f7f1",
            "100": "#dceede",
            "200": "#b8ddb9",
            "300": "#8bc98d",
            "400": "#5ab35d",
            "500": "#3a9a3e",
            "600": "#2e7d32",
            "700": "#256929",
            "800": "#1b5e20",
            "900": "#0d3311",
            "950": "#071a09",
        },
    },
}
