"""
Django settings for County Landing - Home Sales Application Portal.

Generated by 'django-admin startproject' using Django 6.0.2.
"""

import os
from pathlib import Path

import dj_database_url
from django.urls import reverse_lazy
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Security
_INSECURE_KEY = "django-insecure-dev-only-change-in-production"
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", _INSECURE_KEY)
DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() in ("true", "1", "yes")

# Fail loud if insecure key reaches production
if not DEBUG and SECRET_KEY == _INSECURE_KEY:
    raise RuntimeError(
        "DJANGO_SECRET_KEY must be set in production. "
        "Generate one with: python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'"
    )
ALLOWED_HOSTS = os.getenv(
    "DJANGO_ALLOWED_HOSTS",
    "localhost,127.0.0.1",
).split(",")

CSRF_TRUSTED_ORIGINS = os.getenv(
    "CSRF_TRUSTED_ORIGINS",
    "http://localhost:8000,http://127.0.0.1:8000,"
    "http://localhost:8199,http://127.0.0.1:8199,"
    "https://apply.thelandbank.org,"
    "https://apply-thelandbankorg.up.railway.app",
).split(",")


# Application definition

INSTALLED_APPS = [
    # Unfold must come BEFORE django.contrib.admin
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    # Django core
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    # Third-party
    "django_htmx",
    "django_cotton.apps.SimpleAppConfig",
    "template_partials",
    "crispy_forms",
    "anymail",
    "storages",
    # Tailwind theme app
    "tailwind",
    "theme",
    # Custom crispy template pack
    "crispy_gclba",
    # Local apps
    "applications",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            "loaders": [
                (
                    "template_partials.loader.Loader",
                    [
                        "django_cotton.cotton_loader.Loader",
                        "django.template.loaders.filesystem.Loader",
                        "django.template.loaders.app_directories.Loader",
                    ],
                ),
            ],
            "builtins": [
                "django_cotton.templatetags.cotton",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# Uses DATABASE_URL in production (Railway sets this automatically)
# Falls back to SQLite for local development

DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization

LANGUAGE_CODE = "en-us"
TIME_ZONE = "America/New_York"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# WhiteNoise serves these in production without nginx

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# Media files (uploaded documents, images)
# Uses S3-compatible storage in production when AWS_STORAGE_BUCKET_NAME is set,
# falls back to local filesystem for development.
# Works with AWS S3 and Railway's built-in S3-compatible bucket.

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Railway bucket plugin sets AWS_S3_BUCKET_NAME; our original spec uses AWS_STORAGE_BUCKET_NAME.
# Accept either so the Railway "Connect Service to Bucket" dialog works without renaming.
AWS_STORAGE_BUCKET_NAME = os.getenv(
    "AWS_STORAGE_BUCKET_NAME",
    os.getenv("AWS_S3_BUCKET_NAME", ""),
)
if AWS_STORAGE_BUCKET_NAME:
    STORAGES["default"] = {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    }
    AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
    # Railway sets AWS_DEFAULT_REGION; standard is AWS_S3_REGION_NAME
    AWS_S3_REGION_NAME = os.getenv(
        "AWS_S3_REGION_NAME",
        os.getenv("AWS_DEFAULT_REGION", "us-east-1"),
    )
    AWS_S3_CUSTOM_DOMAIN = os.getenv("AWS_S3_CUSTOM_DOMAIN", "")
    # Railway bucket uses a custom endpoint (not s3.amazonaws.com)
    _s3_endpoint = os.getenv("AWS_S3_ENDPOINT_URL", "")
    if _s3_endpoint:
        AWS_S3_ENDPOINT_URL = _s3_endpoint
    AWS_DEFAULT_ACL = None  # Private by default - access via pre-signed URLs only
    AWS_S3_FILE_OVERWRITE = False  # Never overwrite existing files
    AWS_QUERYSTRING_EXPIRE = 900  # Pre-signed URLs expire in 15 minutes
    AWS_S3_OBJECT_PARAMETERS = {
        "CacheControl": "max-age=86400",
    }


# Default primary key field type

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom user model - always define at project start
AUTH_USER_MODEL = "applications.User"


# Email - Resend via Anymail in production, console backend for development

EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)
ANYMAIL = {
    "RESEND_API_KEY": os.getenv("RESEND_API_KEY", ""),
}
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "applications@thelandbank.org")
STAFF_NOTIFICATION_EMAIL = os.getenv("STAFF_NOTIFICATION_EMAIL", "offers@thelandbank.org")


# ---------------------------------------------------------------------------
# Security headers - always-on and production-only settings
# ---------------------------------------------------------------------------

SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Railway is a reverse proxy - trust X-Forwarded-Proto
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# ---------------------------------------------------------------------------
# Django Unfold - Admin Theme Configuration
# ---------------------------------------------------------------------------

UNFOLD = {
    "SITE_TITLE": "GCLBA Application Portal",
    "SITE_HEADER": "Genesee County Land Bank",
    "SITE_SUBHEADER": "Application Management",
    "SITE_SYMBOL": "home_work",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": False,

    # Environment indicator (shows "Development" or "Production" badge in header)
    "ENVIRONMENT": "applications.admin_utils.environment_callback",

    # Dashboard stat cards (shown on admin index page)
    "DASHBOARD_CALLBACK": "applications.admin_utils.dashboard_callback",

    # Sidebar navigation with quick filters
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Applications",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "Dashboard",
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                    {
                        "title": "All Applications",
                        "icon": "description",
                        "link": reverse_lazy("admin:applications_application_changelist"),
                        "badge": "applications.admin_utils.pending_count_badge",
                    },
                    {
                        "title": "Drafts (In Progress)",
                        "icon": "edit_note",
                        "link": reverse_lazy("admin:applications_applicationdraft_changelist"),
                    },
                ],
            },
            {
                "title": "Quick Filters",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Needs Review",
                        "icon": "pending_actions",
                        "link": "/admin/applications/application/?status__exact=received",
                    },
                    {
                        "title": "Unassigned Queue",
                        "icon": "person_off",
                        "link": "/admin/applications/application/?status__exact=received&assigned_to__isnull=True",
                    },
                    {
                        "title": "Under Review",
                        "icon": "rate_review",
                        "link": "/admin/applications/application/?status__exact=under_review",
                    },
                    {
                        "title": "Needs More Info",
                        "icon": "upload_file",
                        "link": "/admin/applications/application/?status__exact=needs_more_info",
                    },
                    {
                        "title": "Approved",
                        "icon": "check_circle",
                        "link": "/admin/applications/application/?status__exact=approved",
                    },
                    {
                        "title": "Declined",
                        "icon": "cancel",
                        "link": "/admin/applications/application/?status__exact=declined",
                    },
                    {
                        "title": "Missing Docs",
                        "icon": "folder_off",
                        "link": "/admin/applications/application/?docs_state=missing",
                    },
                ],
            },
            {
                "title": "Property Inventory",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "All Properties",
                        "icon": "home_work",
                        "link": reverse_lazy("admin:applications_property_changelist"),
                        "badge": "applications.admin_utils.available_properties_badge",
                    },
                    {
                        "title": "Available",
                        "icon": "check_circle",
                        "link": "/admin/applications/property/?status__exact=available",
                    },
                    {
                        "title": "Under Offer",
                        "icon": "handshake",
                        "link": "/admin/applications/property/?status__exact=under_offer",
                    },
                ],
            },
            {
                "title": "System",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Users",
                        "icon": "people",
                        "link": reverse_lazy("admin:applications_user_changelist"),
                    },
                ],
            },
        ],
    },

    # Theme: civic green primary with blue accents
    "COLORS": {
        "primary": {
            "50": "#f0f7f1",
            "100": "#dceede",
            "200": "#b8ddb9",
            "300": "#8bc98d",
            "400": "#5ab35d",
            "500": "#3a9a3e",
            "600": "#2e7d32",
            "700": "#256929",
            "800": "#1b5e20",
            "900": "#0d3311",
            "950": "#071a09",
        },
    },
}


# ---------------------------------------------------------------------------
# Crispy Forms — custom GCLBA template pack
# ---------------------------------------------------------------------------

CRISPY_TEMPLATE_PACK = "gclba"


# ---------------------------------------------------------------------------
# django-tailwind — compiled CSS build
# ---------------------------------------------------------------------------

TAILWIND_APP_NAME = "theme"
INTERNAL_IPS = ["127.0.0.1"]


# ---------------------------------------------------------------------------
# Logging — capture errors in production (DEBUG=False swallows them otherwise)
# ---------------------------------------------------------------------------

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} {levelname} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}
